# Generated by Django 3.0.7 on 2020-06-19 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='投票内容')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('num', models.IntegerField(blank=True, default=0, null=True, verbose_name='投票数')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '微博投票',
                'db_table': 'k_blog_choices',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('type', models.PositiveIntegerField(choices=[(0, '文字'), (1, '投票'), (2, '转发')], default=0, verbose_name='类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='微博内容')),
                ('vote_title', models.TextField(blank=True, null=True, verbose_name='投票标题')),
                ('goodfingers', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
                ('state', models.PositiveIntegerField(choices=[(0, '正常'), (1, '隐藏')], default=0, verbose_name='状态')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.Blogs', verbose_name='转发微博id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogs_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '微博',
                'db_table': 'k_blogs',
            },
        ),
        migrations.CreateModel(
            name='SelectBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('answer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selectBlog_answer', to='group.BlogChoices', verbose_name='投票id')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selectBlog_blog', to='group.Blogs', verbose_name='微博id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selectBlog_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '投票微博',
                'db_table': 'k_select_blogs',
            },
        ),
        migrations.CreateModel(
            name='GoodFingerBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goodFingerBlog_blog', to='group.Blogs', verbose_name='微博id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goodFingerBlog_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '点赞微博',
                'db_table': 'k_goodfinger_blogs',
            },
        ),
        migrations.CreateModel(
            name='CollectBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectBlog_blog', to='group.Blogs', verbose_name='微博id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectBlog_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '收藏微博',
                'db_table': 'k_collect_blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='微博图片')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogImages_blog', to='group.Blogs', verbose_name='微博id')),
            ],
            options={
                'verbose_name': '微博图片',
                'db_table': 'k_blog_images',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否发布')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogComment_blog', to='group.Blogs', verbose_name='微博id')),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogComment_reply', to='user.BaseUser', verbose_name='回复用户id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogComment_user', to='user.BaseUser', verbose_name='留言用户id')),
            ],
            options={
                'verbose_name': '微博留言和回复',
                'db_table': 'k_blog_comment',
            },
        ),
        migrations.AddField(
            model_name='blogchoices',
            name='blog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogChoice_blog', to='group.Blogs', verbose_name='微博id'),
        ),
        migrations.CreateModel(
            name='Blacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('black_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='black_black', to='user.BaseUser', verbose_name='黑名单用户id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='black_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '黑名单',
                'db_table': 'k_blacks',
            },
        ),
        migrations.CreateModel(
            name='Attentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('star_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attentions_star', to='user.BaseUser', verbose_name='关注用户id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attentions_user', to='user.BaseUser', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '关注',
                'db_table': 'k_attentions',
            },
        ),
    ]
