# Generated by Django 3.0.7 on 2020-06-18 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='邮箱')),
                ('token', models.CharField(blank=True, max_length=20, null=True, verbose_name='验证码')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '验证码',
                'db_table': 'k_user_token',
            },
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('account', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='账号用户名')),
                ('status', models.PositiveIntegerField(choices=[(0, '在线'), (1, '黑名单'), (2, '删除')], default=0, verbose_name='状态')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='邮箱')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '管理员',
                'db_table': 'k_manage',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('account', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='账号用户名')),
                ('status', models.PositiveIntegerField(choices=[(0, '在线'), (1, '黑名单'), (2, '删除')], default=0, verbose_name='状态')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='邮箱')),
                ('openid', models.CharField(blank=True, max_length=255, null=True, verbose_name='openID')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人签名')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '基础用户',
                'db_table': 'k_baseuser',
            },
        ),
    ]
